name: Deploy Dash App to Render

on:
  push:
    branches:
      - main  # or "master" if your branch is named that

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run basic test (optional)
      run: python -c "import dash"

    # Optional: Ping Render webhook to trigger deploy
    - name: Trigger Render Deploy Hook
      run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"