# This file set up the Deploy Dash App to Render workflow on GitHub Actions
name: Deploy Dash App to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run basic test (optional)
      run: python -c "import dash"

    # Ping Render webhook to trigger deploy.
    # Reads RENDER_DEPLOY_HOOK_URL from Actions secrets and variables
    - name: Trigger Render Deploy Hook
      run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
